### PR TITLE
Modified MainForm.cs with TXT export by button

### PR DESCRIPTION
**Pull request by vladimir-md**
This is modified MainForm.cs file, that allows to export processed data to a TXT file using button click
Also removed block for exact "unins000.dat" file name, some time sit could be unins001.dat or unins002.dat

### CODE REVIEW

**Comment by preseverence** [comment]
You must follow git rules to make a PR - apply changes to required files (not to some trash files nearby) and check what you've done. Your changes killed all formatting, you know?

Save to txt and altered filter for `uninsXXX` are added in f72e9db605515ec01bcf3ec695c3684f69310742

**Comment by vladimir-md** [comment]
Sorry, this is my first experience with Git, next time will do it carefully :)
Thanks for great work and modification done, this is very appreciated.
Nevertheless, code with export is much more useful. 
Best will be to include compiled EXE file for users, who is far from programming.

**Comment by preseverence** [comment]
I'm not sure that people who are far for programming will read inno uninstall logs..

**Comment by vladimir-md** [comment]
From my point of view, it could be useful for sysadmins or advanced users for manual uninstall or to find hidden of unusually placed application files. Inno is very popular SW.

**Comment by preseverence** [comment]
That makes sense.

https://github.com/preseverence/isulr/releases/tag/1.0

**Comment by vladimir-md** [comment]
Well done! Nice working!
Only two small comments, if you could accept it:
1) at me personally drag&drop is not working now, but file opening is OK;
2) will be best to make little modification in new menu added, now it is located at bottom right angle new new small picture icon, not very intuitive. Best will be to put menu on top left, as usual is done, like File->Export to TXT // Open Log // Exit. 
But all this is only my opinion.

**Comment by preseverence** [comment]
Hmm. I had to test d&d...

I know. This is just to make it work at least somehow and be somehow accessible.

Concerning your advice about users - if there are people who really need that (which is a surprise) - UI should be reworked. Export to CSV (along with TXT), open file from log in explorer, etc. Different features should be added.

But it was more than year since this code was written and you are the only one who tried it.. there will be not many of that people. And this way I am not sure that it is worth to be improved.

**Pull request closed without merging**
